typescript-viem: Number `1_000_000_000_000` is not a valid decimal number. (#224)
trying to deploy typescript-viem's MyToken, I get the following error: 

```
✔ Confirm deploy to network polkadotHubTestnet (420420422)? … yes
An unexpected error occurred:

InvalidDecimalNumberError: Number `1_000_000_000_000` is not a valid decimal number.

Version: viem@2.31.7
    at parseUnits (/Users/cornholio/dev/tmp/hardhat-example-2/node_modules/viem/utils/unit/parseUnits.ts:19:11)
    at parseEther (/Users/cornholio/dev/tmp/hardhat-example-2/node_modules/viem/utils/unit/parseEther.ts:20:20)
    at Object.<anonymous> (/Users/cornholio/dev/tmp/hardhat-example-2/ignition/modules/MyToken.ts:7:42)
    at Module._compile (node:internal/modules/cjs/loader:1562:14)
    at Module.m._compile (/Users/cornholio/dev/tmp/hardhat-example-2/node_modules/ts-node/src/index.ts:1618:23)
    at node:internal/modules/cjs/loader:1699:10
    at Object.require.extensions.<computed> [as .ts] (/Users/cornholio/dev/tmp/hardhat-example-2/node_modules/ts-node/src/index.ts:1621:12)
    at Module.load (node:internal/modules/cjs/loader:1313:32)
    at node:internal/modules/cjs/loader:1123:12
    at Function.module_1.default._load (/Users/cornholio/dev/tmp/hardhat-example-2/node_modules/@parity/hardhat-polkadot/src/sizeCheckPatch.ts:24:24) {
  details: undefined,
  docsPath: undefined,
  metaMessages: undefined,
  shortMessage: 'Number `1_000_000_000_000` is not a valid decimal number.',
  version: '2.31.7'
}
```