Removing `bundledDependencies`
Both `npm` and `pnpm` behave buggy with these, skipping their
dependencies.
Then, because smart contract project will probably have some versions of
ethers or lru-cache, we're getting errors like these:
```
TypeError: lru_cache_1.LRUCache is not a constructor
```

As `@parity/hardhat-polkadot-node` and `@parity/hardhat-polkadot-resolc`
are in dependencies or `@parity/hardhat-polkadot`, they will be
installed automatically.

Do these serve the purpose of eased local development?